//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korting
    {
        public int Id { get; set; }
        public string KortingCode { get; set; }
        public System.DateTime BeginDatum { get; set; }
        public System.DateTime EindDatum { get; set; }
        public double Percentage { get; set; }
        public int ProductMerkId { get; set; }
    
        public virtual ProductMerk ProductMerk { get; set; }
    }
}
