//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMerk
    {
        public ProductMerk()
        {
            this.Korting = new HashSet<Korting>();
            this.BoodschappenProduct = new HashSet<BoodschappenProduct>();
            this.ReceptProduct = new HashSet<ReceptProduct>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string MerkNaam { get; set; }
        public double Prijs { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Merk Merk { get; set; }
        public virtual ICollection<Korting> Korting { get; set; }
        public virtual ICollection<BoodschappenProduct> BoodschappenProduct { get; set; }
        public virtual ICollection<ReceptProduct> ReceptProduct { get; set; }
    }
}
