//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recept
    {
        public Recept()
        {
            this.ReceptProduct = new HashSet<ReceptProduct>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<ReceptProduct> ReceptProduct { get; set; }
    }
}
