//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppieDBEntities : DbContext
    {
        public AppieDBEntities()
            : base("name=AppieDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afdeling> AfdelingSet { get; set; }
        public virtual DbSet<BoodschappenLijst> BoodschappenLijstSet { get; set; }
        public virtual DbSet<BoodschappenProduct> BoodschappenProductSet { get; set; }
        public virtual DbSet<Korting> KortingSet { get; set; }
        public virtual DbSet<Merk> MerkSet { get; set; }
        public virtual DbSet<ProductMerk> ProductMerkSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Recept> ReceptSet { get; set; }
    }
}
