//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMerk = new HashSet<ProductMerk>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string AfdelingNaam { get; set; }
    
        public virtual Afdeling Afdeling { get; set; }
        public virtual ICollection<ProductMerk> ProductMerk { get; set; }
    }
}
